/**
 * Directory-tree walk for review-ia's tier-2 fallback (and for filling
 * in autogenerated Docusaurus sidebar categories under tier 1/3). Walks
 * a docs root on disk, collecting every .md/.mdx file with its relative
 * path, nesting depth, and front matter, plus which directories carry a
 * Docusaurus _category_.json. Read-only: this module never executes
 * anything from the docs repo, and reads files as text only.
 *
 * Exports:
 * - walkDocsTree(absDocsRoot): returns { files, categoryFiles }.
 *   `files` is an array of { relPath, depth, dirParts, baseName, title,
 *   frontmatter }, `relPath` using forward slashes regardless of OS.
 *   `depth` is the number of directory levels under docsRoot (0 for a
 *   file directly in docsRoot). `title` is frontmatter.title, or
 *   frontmatter.sidebar_label, or the base file name if neither is set.
 *   `categoryFiles` is an array of { dirPath (relative), label,
 *   position } read from any `_category_.json` found, skipping ones
 *   that fail to parse as JSON (reported via `error` instead).
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { parseFrontmatter } from "./frontmatter.mjs";

const MARKDOWN_EXTENSIONS = new Set([".md", ".mdx"]);
const IGNORED_DIR_NAMES = new Set([
  "node_modules",
  ".git",
  ".docusaurus",
  "build",
  "dist",
  ".next",
  "results",
]);

function toPosix(p) {
  return p.split(path.sep).join("/");
}

export function walkDocsTree(absDocsRoot) {
  const files = [];
  const categoryFiles = [];

  function visit(absDir, dirParts) {
    let entries;
    try {
      entries = readdirSync(absDir, { withFileTypes: true });
    } catch (error) {
      return; // unreadable directory -- skip rather than crash the whole walk
    }

    const categoryEntry = entries.find((e) => e.isFile() && e.name === "_category_.json");
    if (categoryEntry) {
      const absCategoryPath = path.join(absDir, categoryEntry.name);
      try {
        const parsed = JSON.parse(readFileSync(absCategoryPath, "utf8"));
        categoryFiles.push({
          dirPath: toPosix(dirParts.join("/")),
          label: typeof parsed.label === "string" ? parsed.label : undefined,
          position: typeof parsed.position === "number" ? parsed.position : undefined,
        });
      } catch (error) {
        categoryFiles.push({ dirPath: toPosix(dirParts.join("/")), error: error.message });
      }
    }

    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (IGNORED_DIR_NAMES.has(entry.name) || entry.name.startsWith(".")) continue;
        visit(path.join(absDir, entry.name), [...dirParts, entry.name]);
        continue;
      }

      if (!entry.isFile()) continue;
      const ext = path.extname(entry.name).toLowerCase();
      if (!MARKDOWN_EXTENSIONS.has(ext)) continue;

      const absFilePath = path.join(absDir, entry.name);
      let frontmatter = {};
      try {
        const text = readFileSync(absFilePath, "utf8");
        frontmatter = parseFrontmatter(text).data;
      } catch {
        // unreadable file -- still list it, just with no front matter
      }

      const baseName = entry.name.slice(0, -ext.length);
      const relParts = [...dirParts, entry.name];
      files.push({
        relPath: toPosix(relParts.join("/")),
        depth: dirParts.length,
        dirParts: dirParts.map(toPosix),
        baseName,
        title: frontmatter.title || frontmatter.sidebar_label || baseName,
        frontmatter,
      });
    }
  }

  let rootStat;
  try {
    rootStat = statSync(absDocsRoot);
  } catch {
    return { files: [], categoryFiles: [] };
  }
  if (!rootStat.isDirectory()) {
    return { files: [], categoryFiles: [] };
  }

  visit(absDocsRoot, []);
  return { files, categoryFiles };
}
