#!/usr/bin/env node
/**
 * CLI for review-ia. Parses a docs section's navigation in tiers, and
 * computes deterministic signals over the result -- see
 * docs-gate-claude-code-prompt.md's "Navigation parsing works in
 * tiers" and DEV-NOTES.md. The default tiers NEVER execute any code
 * from the docs repo under review:
 *
 *   1. JSON configs: Mintlify docs.json, Docusaurus sidebars.json (plus
 *      any _category_.json files, used to label directory-fallback
 *      categories and autogenerated-category subtrees).
 *   2. Directory tree fallback (folder structure and front matter).
 *   3. Docusaurus sidebars.js, parsed STATICALLY (see
 *      sidebars-js-static.mjs) only when that's reliable without
 *      executing it; otherwise this script falls back to tier 2 and
 *      says so in its output. Actually executing sidebars.js is a
 *      separate, opt-in script -- see execute-sidebars.mjs.
 *
 * Usage: node analyze-ia.mjs <docs-root>
 * Output: one JSON object on stdout describing the tier used, the
 * parsed nav (when a config was found), the full disk-tree listing,
 * and the deterministic ia-signals.mjs results. Final judgment (is an
 * orphan candidate really orphaned, is a naming mismatch really a
 * problem, is a missing-page signal really missing) is left to the
 * calling skill's model reasoning, not this script.
 * Exit codes: 0 on success; 1 with a message on stderr if the given
 * docs-root doesn't exist or isn't a directory.
 */

import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { walkDocsTree } from "./lib/docs-tree.mjs";
import { parseDocusaurusSidebars } from "./lib/nav-docusaurus.mjs";
import { parseMintlifyNav } from "./lib/nav-mintlify.mjs";
import { parseSidebarsJsStatic } from "./lib/sidebars-js-static.mjs";
import {
  normalizeSlug,
  computeOrphanCandidates,
  computeDepthSignals,
  computeNamingSignals,
  computeExpectedPageSignals,
} from "./lib/ia-signals.mjs";

const docsRootArg = process.argv[2];
if (!docsRootArg) {
  console.error("Usage: node analyze-ia.mjs <docs-root>");
  process.exit(1);
}

const absDocsRoot = path.resolve(docsRootArg);
if (!existsSync(absDocsRoot) || !statSync(absDocsRoot).isDirectory()) {
  console.error(`Not a directory: ${absDocsRoot}`);
  process.exit(1);
}

function readJsonIfPresent(absPath) {
  if (!existsSync(absPath)) return { present: false };
  try {
    return { present: true, value: JSON.parse(readFileSync(absPath, "utf8")) };
  } catch (error) {
    return { present: true, error: error.message };
  }
}

const notes = [];
const { files: diskFiles, categoryFiles } = walkDocsTree(absDocsRoot);

// --- Tier 1: JSON configs -------------------------------------------------
const docsJson = readJsonIfPresent(path.join(absDocsRoot, "docs.json"));
const sidebarsJson = readJsonIfPresent(path.join(absDocsRoot, "sidebars.json"));

let tier = null;
let navSource = null;
let navEntries = [];

if (docsJson.present && !docsJson.error) {
  tier = 1;
  navSource = "mintlify:docs.json";
  const result = parseMintlifyNav(docsJson.value);
  navEntries = result.entries;
  notes.push(...result.notes);
} else if (docsJson.error) {
  notes.push(`docs.json present but failed to parse as JSON: ${docsJson.error}`);
}

if (tier === null && sidebarsJson.present && !sidebarsJson.error) {
  tier = 1;
  navSource = "docusaurus:sidebars.json";
  const result = parseDocusaurusSidebars(sidebarsJson.value);
  navEntries = result.entries;
  notes.push(...result.notes);
} else if (sidebarsJson.error) {
  notes.push(`sidebars.json present but failed to parse as JSON: ${sidebarsJson.error}`);
}

// --- Tier 3 (attempted before falling all the way back to tier 2): --------
// a static, non-executing parse of sidebars.js, only when no JSON config
// was already found above.
const sidebarsJsPath = path.join(absDocsRoot, "sidebars.js");
let sidebarsJsStaticNote = null;
if (tier === null && existsSync(sidebarsJsPath)) {
  const source = readFileSync(sidebarsJsPath, "utf8");
  const attempt = parseSidebarsJsStatic(source);
  if (attempt.ok) {
    tier = 3;
    navSource = "docusaurus:sidebars.js (parsed statically)";
    const result = parseDocusaurusSidebars(attempt.value);
    navEntries = result.entries;
    notes.push(...result.notes);
  } else {
    sidebarsJsStaticNote = attempt.reason;
    notes.push(
      `Found sidebars.js but could not parse it statically (${attempt.reason}). Falling back to the directory tree. Executing sidebars.js is opt-in -- see execute-sidebars.mjs -- and runs code from the repo under review.`
    );
  }
}

// --- Tier 2: directory tree fallback --------------------------------------
if (tier === null) {
  tier = 2;
  navSource = "directory tree";
  notes.push(
    docsJson.present || sidebarsJson.present
      ? "A config file was present but unusable; used the directory tree instead."
      : "No docs.json or sidebars.json found; used the directory tree."
  );
}

// --- Expand any autogenerated Docusaurus categories using the disk tree --
// so their pages aren't reported as orphans just because the config names
// a directory instead of listing pages explicitly.
const referencedSlugs = new Set();
for (const entry of navEntries) {
  if (entry.kind === "doc" && entry.docId) {
    referencedSlugs.add(normalizeSlug(entry.docId));
  } else if (entry.kind === "page" && entry.slug) {
    referencedSlugs.add(normalizeSlug(entry.slug));
  } else if (entry.kind === "autogenerated" && entry.dirName) {
    const prefix = normalizeSlug(entry.dirName);
    for (const file of diskFiles) {
      const slug = normalizeSlug(file.relPath);
      if (slug === prefix || slug.startsWith(`${prefix}/`)) {
        referencedSlugs.add(slug);
      }
    }
  }
}

// --- Deterministic signals (only meaningful to compare against a real
// config-based nav; tier-2-only runs have no separate "nav" to diff
// against, so orphan candidates are skipped rather than reported as 100%
// of files ------------------------------------------------------------
const signals = {
  orphanCandidates: tier === 2 ? [] : computeOrphanCandidates(diskFiles, referencedSlugs),
  depthSignals: computeDepthSignals(diskFiles),
  namingSignals: computeNamingSignals(diskFiles),
  expectedPageSignals: computeExpectedPageSignals(diskFiles),
};

process.stdout.write(
  JSON.stringify(
    {
      docsRoot: absDocsRoot,
      tier,
      navSource,
      navEntryCount: navEntries.length,
      navEntries,
      diskFileCount: diskFiles.length,
      diskFiles,
      categoryFiles,
      sidebarsJsStaticNote,
      notes,
      signals,
    },
    null,
    2
  )
);
process.exit(0);
