import { test } from "node:test";
import assert from "node:assert/strict";
import { parseDocusaurusSidebars } from "../../plugins/docs-gate/scripts/lib/nav-docusaurus.mjs";

test("flattens bare doc ID strings", () => {
  const { entries } = parseDocusaurusSidebars({ main: ["intro", "guide"] });
  assert.deepEqual(
    entries.map((e) => e.docId),
    ["intro", "guide"]
  );
});

test("recurses into a category and tracks depth", () => {
  const { entries } = parseDocusaurusSidebars({
    main: [{ type: "category", label: "Guides", items: ["guides/one", "guides/two"] }],
  });
  const category = entries.find((e) => e.kind === "category");
  const docs = entries.filter((e) => e.kind === "doc");
  assert.equal(category.label, "Guides");
  assert.equal(category.depth, 0);
  assert.deepEqual(
    docs.map((e) => e.docId),
    ["guides/one", "guides/two"]
  );
  assert.ok(docs.every((e) => e.depth === 1));
});

test("notes an autogenerated category instead of guessing its contents", () => {
  const { entries, notes } = parseDocusaurusSidebars({
    main: [{ type: "autogenerated", dirName: "guides" }],
  });
  assert.equal(entries[0].kind, "autogenerated");
  assert.equal(entries[0].dirName, "guides");
  assert.ok(notes.some((n) => n.includes("autogenerated")));
});

test("notes a category with no items and no generated-index link", () => {
  const { notes } = parseDocusaurusSidebars({
    main: [{ type: "category", label: "Empty" }],
  });
  assert.equal(notes.length, 0); // no items and no generated-index link: silently empty category, not an error
});

test("handles link items", () => {
  const { entries } = parseDocusaurusSidebars({
    main: [{ type: "link", label: "External", href: "https://example.com" }],
  });
  assert.equal(entries[0].kind, "link");
  assert.equal(entries[0].href, "https://example.com");
});

test("notes and skips an unrecognized item type", () => {
  const { entries, notes } = parseDocusaurusSidebars({
    main: [{ type: "html", value: "<hr/>" }],
  });
  assert.equal(entries[0].kind, "unknown");
  assert.ok(notes.some((n) => n.includes("html")));
});

test("skips a non-array sidebar with a note", () => {
  const { entries, notes } = parseDocusaurusSidebars({ main: "not an array" });
  assert.deepEqual(entries, []);
  assert.ok(notes.some((n) => n.includes("main")));
});

test("handles multiple sidebars", () => {
  const { entries } = parseDocusaurusSidebars({ first: ["a"], second: ["b"] });
  assert.deepEqual(
    entries.map((e) => [e.sidebarId, e.docId]),
    [
      ["first", "a"],
      ["second", "b"],
    ]
  );
});
